"""Cricket-aware VADER expansions. Values follow VADER's roughly [-4, 4] lexicon scale."""

from __future__ import annotations

import re

# Multiword cricket phrases become single lexicon tokens before scoring.
PHRASE_MAP: tuple[tuple[str, str], ...] = (
    (r"golden duck", "goldenduck"),
    (r"wicket maiden", "wicketmaiden"),
    (r"maiden over", "maidenover"),
    (r"dropped catch", "droppedcatch"),
    (r"dropped it", "droppedcatch"),
    (r"what a six", "whatasix"),
    (r"what a shot", "whatashot"),
    (r"what a catch", "whatacatch"),
    (r"hat[- ]?trick", "hattrick"),
    (r"hatrick", "hattrick"),
    (r"free hit", "freehit"),
    (r"death overs?", "deathovers"),
    (r"powerplay", "powerplay"),
    (r"super over", "superover"),
    (r"run[- ]?out", "runout"),
    (r"no[- ]?ball", "noball"),
    (r"leg bye", "legbye"),
    (r"thala for a reason", "thalaforareason"),
    (r"ee sala cup namde", "eesalacupnamde"),
    (r"send it", "sendit"),
    (r"into the stands", "intothestands"),
    (r"clean bowled", "cleanbowled"),
    (r"plumb lbw", "plumblbw"),
    (r"middle stump", "middlestump"),
    (r"knuckle ball", "knuckleball"),
    (r"slow ball", "slowball"),
    (r"short ball", "shortball"),
    (r"full toss", "fulltoss"),
    (r"last over", "lastover"),
    (r"final over", "lastover"),
    (r"choked in death", "chokedindeath"),
    (r"bottled it", "bottledit"),
    (r"threw it away", "threwitaway"),
    (r"smashed a four", "smashedafour"),
    (r"smashed a six", "smashedasix"),
)

CRICKET_LEXICON: dict[str, float] = {
    # Scoring / batting good
    "six": 2.8,
    "sixer": 2.8,
    "sixes": 2.4,
    "maximum": 2.2,
    "whatasix": 3.2,
    "smashedasix": 3.0,
    "four": 2.0,
    "fours": 1.8,
    "boundary": 1.8,
    "boundaries": 1.6,
    "smashedafour": 2.4,
    "whatashot": 2.8,
    "strike": 0.6,
    "strikerate": 0.4,
    "intothestands": 2.6,
    "sendit": 1.8,
    "blazing": 1.6,
    "onfire": 1.8,
    "unplayable": 2.0,
    "class": 1.4,
    "knock": 0.8,
    "anchor": 0.8,
    "finisher": 1.2,
    "finishing": 1.0,
    "freehit": 1.6,
    "superover": 1.0,
    # Bowling good / batting bad
    "yorker": 1.6,
    "yolker": 1.4,
    "bouncer": 0.6,
    "inswinger": 1.0,
    "outswinger": 1.0,
    "googly": 0.8,
    "doosra": 0.8,
    "knuckleball": 1.2,
    "slowerball": 0.8,
    "slowball": 0.6,
    "maiden": 1.4,
    "maidenover": 1.8,
    "wicketmaiden": 2.6,
    "wicket": 1.2,
    "wickets": 1.0,
    "goldenduck": -3.2,
    "duck": -2.2,
    "ducks": -1.8,
    "cleanbowled": 2.2,
    "bowled": 1.2,
    "plumblbw": 1.8,
    "lbw": 1.0,
    "middlestump": 1.6,
    "hattrick": 2.8,
    "runout": -1.6,
    "stumped": -1.4,
    "caught": -0.8,
    "whatacatch": 2.6,
    "screamer": 2.2,
    "droppedcatch": -2.4,
    "drop": -1.2,
    "dropped": -1.6,
    "misfield": -1.4,
    "overthrow": -0.8,
    "wide": -0.6,
    "wides": -0.6,
    "noball": -1.2,
    "noballs": -1.0,
    "fulltoss": -0.8,
    "beamer": -1.8,
    # Match situation
    "collapse": -2.6,
    "collapsing": -2.4,
    "choke": -2.8,
    "choked": -2.8,
    "chokedindeath": -3.0,
    "bottledit": -2.8,
    "threwitaway": -2.6,
    "deathovers": -0.4,
    "lastover": 0.2,
    "powerplay": 0.4,
    "required": -0.2,
    "dot": -0.4,
    "dots": -0.4,
    "dotball": -0.8,
    "economy": 0.2,
    "expensive": -1.2,
    "hammered": -1.8,
    "smashed": 1.4,
    "tonked": 1.6,
    "dispatched": 1.4,
    "deposited": 1.4,
    "launched": 1.6,
    "helicopter": 1.8,
    "scoop": 1.0,
    "ramp": 1.0,
    "pull": 0.6,
    "coverdrive": 1.2,
    "drive": 0.6,
    "block": -0.2,
    "leave": 0.0,
    "appeal": 0.4,
    "review": 0.2,
    "umpire": 0.0,
    "no": 0.0,
    # Fan lexicon (valence of enthusiasm, not team identity)
    "thala": 1.8,
    "thalaforareason": 2.2,
    "whistlepodu": 1.6,
    "eesalacupnamde": 1.6,
    "rcbian": 0.8,
    "orangearmy": 0.8,
    "yellowarmy": 0.8,
    "knightriders": 0.6,
    "hallabol": 1.2,
}


def normalize_cricket_text(text: str) -> str:
    out = text
    for pattern, token in PHRASE_MAP:
        out = re.sub(pattern, token, out, flags=re.IGNORECASE)
    return out
